INSERT INTO category (type)
VALUES ('Technology'),
    ('Science'),
    ('Sports'),
    ('Music'),
    ('Art'),
    ('Fashion'),
    ('Food'),
    ('Travel'),
    ('Health'),
    ('Business'),
    ('Education'),
    ('Nature'),
    ('Entertainment'),
    ('History'),
    ('Literature'),
    ('Politics'),
    ('Religion'),
    ('Philosophy'),
    ('Gaming'),
    ('Programming'),
    ('Golang'),
    ('Cookies'),
    ('DIY');    